services:
  # Web Application
  web:
    image: drp-web
    build:
       context: ./web
       dockerfile: Dockerfile
    ports:
      - 3030:3000
  
  # Database: Postgres + Adminer for easier access
  db:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB:-drp}

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 9000:8080

  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:8080