services:
  # Web Application
  web:
    image: drp-web
    build:
       context: ./web
       dockerfile: Dockerfile
    ports:
      - 80:3000
  
  # Database: Postgres + Adminer for easier access
  db:
    image: postgres
    restart: always
    ports:
      - 5055:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB:-drp}

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080