name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    name: Build Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose Build
        run: docker compose build
